namespace GoogleGenAI.SDK.Models;

/// <summary>
/// Tool that executes code generated by the model, and automatically returns the result to the model.  See also `ExecutableCode` and `CodeExecutionResult` which are only generated when using this tool.
/// </summary>
public class CodeExecution
{
}