namespace GoogleGenAI.SDK.Models;

/// <summary>
/// Source of the File.
/// </summary>
public enum FileSource
{
    /// <summary>
    /// Used if source is not specified.
    /// </summary>
    SOURCE_UNSPECIFIED,

    /// <summary>
    /// Indicates the file is uploaded by the user.
    /// </summary>
    UPLOADED,

    /// <summary>
    /// Indicates the file is generated by Google.
    /// </summary>
    GENERATED,
}