namespace GoogleGenAI.SDK.Models;

/// <summary>
/// Optional. Output only. The reason why the model stopped generating tokens. If empty, the model has not stopped generating tokens.
/// </summary>
public enum FinishReason
{
    /// <summary>
    /// Default value. This value is unused.
    /// </summary>
    FINISH_REASON_UNSPECIFIED,

    /// <summary>
    /// Natural stop point of the model or provided stop sequence.
    /// </summary>
    STOP,

    /// <summary>
    /// The maximum number of tokens as specified in the request was reached.
    /// </summary>
    MAX_TOKENS,

    /// <summary>
    /// The response candidate content was flagged for safety reasons.
    /// </summary>
    SAFETY,

    /// <summary>
    /// The response candidate content was flagged for recitation reasons.
    /// </summary>
    RECITATION,

    /// <summary>
    /// The response candidate content was flagged for using an unsupported language.
    /// </summary>
    LANGUAGE,

    /// <summary>
    /// Unknown reason.
    /// </summary>
    OTHER,

    /// <summary>
    /// Token generation stopped because the content contains forbidden terms.
    /// </summary>
    BLOCKLIST,

    /// <summary>
    /// Token generation stopped for potentially containing prohibited content.
    /// </summary>
    PROHIBITED_CONTENT,

    /// <summary>
    /// Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
    /// </summary>
    SPII,

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    MALFORMED_FUNCTION_CALL,

    /// <summary>
    /// Token generation stopped because generated images contain safety violations.
    /// </summary>
    IMAGE_SAFETY,
}